version: '3'

networks:
  my_network:
    driver: bridge

services:
  order-processing-service:
    build: C:\Python\order-processing-service
    networks:
      - my_network

  home-page-service:
    build: C:\Python\home-page-service
    networks:
      - my_network
    ports:
      - "5002:5002"

  user-management-service:
    build: C:\Python\user-management-service
    networks:
      - my_network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - my_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
