version: "3"
name: "scamazon"

networks:
  my_network:
    driver: bridge

volumes:
  mongo-data:

services:
  home-page-service:
    build: ./backend
    networks:
      - my_network
    ports:
      - "4004:4004"
    environment:
      - SERVER_PORT=4004
      - USER_URL=user-management-service
      - USER_PORT=4006
      - PRODUCT_URL=product-catalog-service
      - PRODUCT_PORT=4005
      - ORDER_URL=order-processing-service
      - ORDER_PORT=4007