version: '3'
name: "scamazon"

networks:
  my_network:
    driver: bridge

volumes:
  mongo-data:


services:

  home-page-service:
    build: ./backend
    networks:
      - my_network
    ports:
      - "5002:5002"
    depends_on:
      mongo-home-page-service:
        condition: service_healthy

  prometheus-home-page-service:
    image: prom/prometheus:latest
    ports:
      - "9092:9090"
    networks:
      - my_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml

  mongo-home-page-service:
    image: mongo
    restart: always
    networks:
      - my_network
    volumes:
      - ./mongo-data:/data/db
    healthcheck:
      test: echo 'mongo-home-page-service.runCommand("ping").ok' | mongosh mongo-home-page-service:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 40s
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express-home-page-service:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - my_network
    depends_on:
      mongo-home-page-service:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-home-page-service:27017/
