version: '3'
name: "scamazon"

networks:
  my_network:
    driver: bridge

volumes:
  mongo-data:

services:

  home-page-service:
    build: ./backend
    networks:
      - my_network
    ports:
      - "4004:4004"
  
  prometheus-home-page-service:
    image: prom/prometheus:latest
    ports:
      - "9092:9090"
    networks:
      - my_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml
  
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3005:3000
    networks:
      - my_network
    

    

