version: '3'
name: "scamazon"

networks:
  my_network:
    driver: bridge

volumes:
  mongo-data:

services:

  home-page-service:
    build: ./backend
    networks:
      - my_network
    ports:
      - "5002:5002"
  
  prometheus-home-page-service:
    image: prom/prometheus:latest
    ports:
      - "9092:9090"
    networks:
      - my_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml

