name: Docker Build, Push, Deploy to Minikube, and Cypress Tests

on:
  push:
    branches:
      - harisha_homepage_testing

jobs:
  build-and-deploy-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker Image for home-page-service
        run: |
          docker build -t passwordnotsafe/home-page-service ./backend

      - name: Push Docker Image for home-page-service
        run: |
          docker push passwordnotsafe/home-page-service

      - name: Build Docker Image for seed-data
        run: |
          docker build -t passwordnotsafe/seed-data ./script

      - name: Push Docker Image for seed-data
        run: |
          docker push passwordnotsafe/seed-data

      - name: Build Docker Image for mongo-backup
        run: |
          docker build -t passwordnotsafe/mongo-backup ./script/backup

      - name: Push Docker Image for mongo-backup
        run: |
          docker push passwordnotsafe/mongo-backup

      # Deploy to Minikube
      - name: Setup Minikube
        uses: medyagh/setup-minikube@master
        id: minikube
        with:
          driver: docker
          wait: all

      # Debug Minikube IP
      - name: Debug Minikube IP
        run: |
          minikube status
          minikube ip    
         
      # Cypress Tests
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install

      # Wait for Minikube to be ready (add more checks if necessary)
      - name: Wait for Minikube to be ready
        run: |
          minikube status    
      
      # Wait for services to be ready (replace with your service check commands)
      - name: Wait for home-page-service to be ready
        run: |
          sleep 30s # Add appropriate wait time
          docker compose -f home-page-service/docker-compose.yml exec home-page-service curl -f http://localhost:4004/health || exit 1
    
      - name: Run Cypress tests
        run: |
          eval $(minikube -p minikube docker-env)
          npx cypress run --browser chrome --config baseUrl=http://localhost:4004

