name: Docker Build and Push

on:
  push:
    branches:
      - 10-test-github-action-building-docker-image-and-publish

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t passwordnotsafe/home-page-service:1.0.0 ./script

      - name: Push Docker Image
        run: |
          docker push passwordnotsafe/home-page-service:1.0.0

      # build and push the second image also
      - name: Build Docker Image
        run: |
          docker build -t passwordnotsafe/seed-data:test ./script

      - name: Push Docker Image for script
        run: |
          docker push passwordnotsafe/seed-data:test
